config/routes.rb
Rails.application.routes.draw do

  get 'reports/clientdetail'=>'reports#clientdetail'
  get 'reports/transactionhistory'=>'reports#transactionhistory'
  get 'reports/vendordetail'=>'reports#vendordetail'
  get 'reports/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'reports/customersummary'=>'reports#customersummary'
  get 'reports/vendorsummary'=> "reports#vendorsummary"
  get 'reports/bankbalance'=> "reports#bankbalance"
  get 'reports/paymentdetail'=> "reports#paymentdetail"
  get 'reports/cashdetail'=> "reports#cashdetail"
  get 'reports/paymentsummary'=> "reports#paymentsummary"
  get 'reports/cashsummary'=> "reports#cashsummary"

  get 'invoices/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'invoices/summary_invoice/:client_id/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/:date_to'=>'invoices#summary_invoice'
  get 'invoices/invoicesummary'=>'invoices#invoicesummary'

  get 'public/privacy'

  get 'public/conditions'

  resources :transactionbills
  resources :vendortransactions
  resources :transactioninvoices
  resources :clienttransactions
  resources :setups
  resources :setups
  resources :bills
  resources :invoices do
    resources :line_items
  end

  resources :vendors
  resources :clients
  get 'history/index'
  get 'search/index'
  get 'landing' => 'search#landing'

  get 'users/send_email'
  get 'users/notes', as: "get__user_notes"
  post 'users/notes', as: "user_notes"
  get 'users/setup'
  get 'search/results'

  get "user/:id" => "users#user_profile", :as=> "user_profile"
  get 'invoices/invoices_of_a_single_client/:client_id' => 'invoices#invoices_of_a_single_client'
  
  get 'bills/bills_of_a_single_client/:vendor_id' => 'bills#bills_of_a_single_client'
  
  root to: 'search#index'
  devise_for :users
  resources :users
end

app/controllers/clienttransactions_controller.rb
class ClienttransactionsController < ApplicationController
  before_action :set_clienttransaction, only: [:show, :edit, :update, :destroy]

  # GET /clienttransactions
  # GET /clienttransactions.json
  def index
    @clienttransactions = current_user.clienttransactions.order("id DESC")
  end

  # GET /clienttransactions/1
  # GET /clienttransactions/1.json
  def show
  end

  # GET /clienttransactions/new
  def new
    @clienttransaction = Clienttransaction.new
  end

  # GET /clienttransactions/1/edit
  def edit
    @client_transaction = Clienttransaction.find(params[:id])
    @edit_invoice = @client_transaction.invoices    
    @open_invoices = @client_transaction.client.invoices.where(:status => 'unpaid')
  end

  # POST /clienttransactions
  # POST /clienttransactions.json
  def create
    @clienttransaction = Clienttransaction.new(clienttransaction_params)
    @clienttransaction.user_id = current_user.id
    
    respond_to do |format|
      if @clienttransaction.save
        set_formatted_dates()

        ids = params[:invoices]
        ids= ids.split(","); # Split ids because it was
        balances = params[:balances]
        amount = params[:transaction_amount]
        refnum = params[:reference_no]
        cashtype = params[:Cash_type]
        amount.to_f
        ids.zip(balances).each do |id, balance|  #Each loop through two arrays
          @invoice= Invoice.find(id) # Find Invoice id to update balance in invoice table

          @value =  @invoice.totalpaid.to_f + balance.to_f
          Invoice.where(id: id).update_all(totalpaid: @value, balance: (@invoice.amount.to_f - @value.to_f)) # Update total paid against each Invoice id

          Transactioninvoice.create(:invoice_id => id, :clienttransaction_id => @clienttransaction.id,
                                    :balance => balance, :amount=> amount, :reference_no => refnum,
                                    :Cash_type => cashtype, :user_id => current_user.id)

          Invoice.where(id: id, amount: @value).update_all(status: 'paid') # If Invoice amount equals to last paid change status to paid
        end

        format.html { redirect_to clienttransactions_path, notice: 'Transaction was successfully processed.' }
        format.json { render :show, status: :created, location: @clienttransaction }
        format.js{}

      else
        format.html { render :new }
        format.json { render json: @clienttransaction.errors, status: :unprocessable_entity }
        format.js{}

      end
    end
  end

  # PATCH/PUT /clienttransactions/1
  # PATCH/PUT /clienttransactions/1.json
  def update
    respond_to do |format|
      if @clienttransaction.update(clienttransaction_params)
        set_formatted_dates()
        ids = params[:invoices]
        ids = ids.split(",")
        balances = params[:balances]
        amount= params[:transaction_amount]
        amount.to_f

        ids.zip(balances).each do |id, balance|  #Each loop through two arrays
          @invoice = Invoice.find(id)
          @value =  @invoice.totalpaid.to_f + balance.to_f
          Invoice.where(id: id).update_all(totalpaid: @value, balance: (@invoice.amount.to_f - @value.to_f))

          Transactioninvoice.create(invoice_id: id, clienttransaction_id: @clienttransaction.id,
                                    balance: balance, amount: amount)
          Invoice.where(id: id, amount: @value).update_all(status: 'paid')
        end
        format.html { redirect_to clienttransactions_path, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @clienttransaction }
      else
        format.html { render :edit }
        format.json { render json: @clienttransaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /clienttransactions/1
  # DELETE /clienttransactions/1.json
  def destroy
    @clienttransaction.destroy
    respond_to do |format|
      format.html { redirect_to clienttransactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_formatted_dates
      @clienttransaction.update_attribute(:duedate, formatted_date(clienttransaction_params[:duedate])) if clienttransaction_params[:duedate].present?
      @clienttransaction.update_attribute(:transaction_date, formatted_date(clienttransaction_params[:transaction_date])) if clienttransaction_params[:transaction_date].present?
    end

    def set_clienttransaction
      @clienttransaction = Clienttransaction.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def clienttransaction_params
      params.require(:clienttransaction).permit(:setup_id, :client_id,:user_id, :transaction_date, :duedate)
    end
end

app/helpers/clienttransactions_helper.rb
module ClienttransactionsHelper
end

app/views/clienttransactions/_form.html.erb
<%= simple_form_for(@clienttransaction) do |f| %>
  <%= f.error_notification %>
<div class="row">
  <div class="form-inputs col-md-6">

    <%= f.input :transaction_date, :as => :string, class: 'form-control', input_html: { class: 'tdate' } %>
    <%= f.input :duedate, as: :string, required: true, input_html: { class: 'ddate' } %>

    <label>Reference#/Check#/Wire#</label>
      <input type="number" class="form-control" name="reference_no" >
<br>
    <select name="Cash_type" class="form-control">
        <option selected disabled>Select Payment Type</option>
        <option value="Cash">Cash</option>
        <option value="Cheque">Check</option>
        <option value="Wire Transfer">Wire Transfer</option>
        <option value="Credit Card">Credit Card</option>
    </select>
<br>
    <%= f.select_tag "clienttransaction[setup_id]",
                     options_for_select(current_user.setups.where(:setuptype=>'bank').map{|s|[s.typeofsetup, s.id]},
                                        @clienttransaction.setup_id),:id=>"setup_id" , prompt: "Select Bank Account",
                     class: 'form-control' , required: true%>

    <br>
 <%= f.select_tag "clienttransaction[client_id]",
                  options_for_select(current_user.clients.order_by_name.map{|s|[s.company_name, s.id]}, @clienttransaction.client_id),
                  id: "client", prompt: "Select Client", class: 'form-control', id: 'client_id',  required: true %>
  

 <input type="text" hidden name="invoices" class="transaction_invoice_id" value=" "> <!-- Ids of invoices  -->

  <br>
  <label>Total amount</label>
  <!-- Total amount of transaction goes from there  -->
  <input type="number" id="total_blc" class="form-control" value="0.00" name="transaction_amount" readonly="readonly" >
  <br>
  
  </div>
<div class="col-xs-12">
<button type="button" id="show_select" class="btn  btn-info pull-right" data-toggle="modal" data-target="#invoices">Add Invoice</button>
</div>
</div>

<div class="row">
  <div id="divResults">

    <table class="table table-hover table-striped">
      <thead>
        <tr>
          <th >Invoice Num</th>
          <th >Reference</th>
          <th >Amount</th>
          <th >Transaction Amount</th>
          <th >Last Paid</th>
          <th >Due Date</th>
          <th >Total Paid</th>
          <th >Notes</th>
        </tr>
      </thead>

      <tbody id="tbody_empty">
        <% if params[:action] == "edit" %>

          <% @edit_invoice.each do |invoice|%>
          <tr >
            <td><%= invoice.id %></td>
            <td><%= invoice.reference %></td>
            <td><%= number_with_precision(invoice.amount, precision: 2) %></td>
            <td><input type="number" min="0"
                       max="<%= invoice.transactioninvoices.first.balance.to_s %>" name="balances[<%= invoice.id%>]"
                       value="<%= number_with_precision(invoice.transactioninvoices.first.balance, precision: 2) %>"/></td>
            <td><%= invoice.lastpayment %></td>
            <td><%= display_formatted_date(invoice.duedate) %></td>
            <td><%= number_with_precision(invoice.totalpaid, precision: 2) %></td>
            <td><%= invoice.notes %></td>
          </tr>
          <%end%>

        <% end %>
      </tbody>
      
    </table>
  </div>
</div>
<h3 id="nothing_alert">
This Client has No open Invoices
</h3>
<div class="form-actions">
    <%= f.button :submit, "Save", class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/clienttransactions/edit.html.erb
<h1>Editing Clienttransaction</h1>



<script type="text/javascript">
  var invoice_ids=[];
  var invoice_balances=[];

  jQuery(function($) {
    $('#client_id').trigger('change');

    $("#client_id").change(function() {
      $("#tbody_empty").empty();
      $('#total_blc').val(0);
      invoice_ids=[];
      invoice_balances=[];
      var select ="Select";
      var client_id = $('select#client_id :selected').val();
      jQuery.getJSON('/invoices/invoices_of_a_single_client/' + client_id, function(result){
        var invoices_client = "";

        $.each(result, function( index, data ) {

          invoices_client += '<tr> <td class="invoice_num"><a href="/invoices/'+ data.id +'">'+ data.id +
              '</a> </td> <td class="invoice_reference"> '+ data.reference +' </td> <td class="invoice_amount">'+data.amount+
              ' </td><td class="invoice_balance"><input name="balances[]" type="number" min="0" max="'+
              parseFloat(data.balance_amount).toFixed(2) +'" value="' + parseFloat(data.balance_amount).toFixed(2) +'"/> </td> <td class="invoice_lastpayment">'+
              data.lastpayment +' </td> <td class="invoice_duedate">'+ data.duedate +' </td><td class="invoice_totalpaid">'+
              parseFloat(data.totalpaid).toFixed(2) +' </td> <td class="invoice_notes">'+ data.notes +'</td> <td> <a data-invoice-id="'+
              data.id+'" class="btn btn-danger get_invoice_id append_row">Select</a></td></tr>';

        });


        $("#client_invoice tbody").html("");
        $("#client_invoice tbody").html(invoices_client);

      })
      return false;
    });
  })

  $(document).ready(function(){
    $('body').on('change', '.blc', function() {
      // $("#total_blc").val( parseFloat($("#total_blc").val()) + parseFloat($(this).val()) );
      var sum = 0;
      $(".blc").each(function() {
        //add only if the value is number
        if (!isNaN(this.value) && this.value.length != 0) {
          sum += parseFloat(this.value);
        }
      });
      $("#total_blc").val( sum );
    });
  });


  $(document).ready(function(){

    $("#divResults table tbody").bind("DOMSubtreeModified", function() {
      if( $(this).children().length > 0 )
        $('input[type="submit"]').show();
      else
        $('input[type="submit"]').hide();
    });
    $('body').on('click', '.append_row', function() {

      var actual = $(this).parent().parent();
      $(this).remove();
      actual.find('[name="balances[]"]').addClass("blc");

      value = actual.find('.blc').val();
      if (!isNaN(value) && value.length != 0) {
        $("#total_blc").val( parseFloat( $("#total_blc").val() ) + parseFloat(value) );
      }

      $('#divResults table tbody').append(actual);
      $('#invoices').modal('hide');
      // $('input[type="submit"]').show();

      var invoice_id = actual.find(".invoice_num").text(); //Invoice ids
      invoice_ids.push(invoice_id); //Id push in array
      $('.transaction_invoice_id').val(invoice_ids); // SEnd to hidden field in form
    });
    $(function() {
      $('#client_id').change(function(){
        $('#divResults').show('2000');
      });
    });

  });

</script>

<%= render 'form' %>




<div id="invoices" class="modal fade col-xs-10"  role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-xs-12" style="width:150%">
      <div class="modal-header">
        <h3>Select Invoice</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <table class="table table-hover" id="client_invoice">
          <thead>
          <tr>
            <th >Invoice Num</th>
            <th >Reference</th>
            <th >Amount</th>
            <th >Transaction Amount</th>
            <th >Last Paid</th>
            <th >Due Date</th>
            <th >Total Paid</th>
            <th >Notes</th>
          </tr>
          </thead>

          <tbody>
          </tbody>

        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script>
  $(function() {
    $(".tdate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date());
    $(".ddate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date(Date.now() + (30 * 24 * 60 * 60 * 1000)));
  });
</script>

app/views/clienttransactions/index.html.erb
<h1>Cash From Clients</h1>


<table class="table table-hover table-striped">
  <%= link_to 'New Transaction', new_clienttransaction_path,
 class: "btn btn-primary pull-right new-btn-top-right text-right" %> 
  <thead>
    <tr>
      <th>Transaction Id</th>
      <th>Reference#/Check#/Wire#</th>
      <th>Client Name</th>
      <th>Bank Account</th>
      <th>Payment Type</th>
      <th>Transaction Date</th>
      <th>Due Date</th>
      <th>Invoices</th>
      <th>Amount</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @clienttransactions.each do |clienttransaction| %>
      <tr>
        <% transaction_invoice = Transactioninvoice.where(:clienttransaction_id=>clienttransaction.id) %>
        <td><%= clienttransaction.id %></td>
        <td><%= transaction_invoice.present? ? transaction_invoice.first.reference_no : '---' %></td>

        <td><%=  clienttransaction.client.present? ? clienttransaction.client.company_name : '---' %></td>
        <td><%=  clienttransaction.setup.present? ? clienttransaction.setup.typeofsetup : '---' %></td>
        <td><%= transaction_invoice.present? ? transaction_invoice.first.Cash_type: '---' %></td>
        <td><%= display_formatted_date(clienttransaction.transaction_date) %></td>
        <td><%= display_formatted_date(clienttransaction.duedate) %></td>
        <td><%= transaction_invoice.present? ? transaction_invoice.count : '---' %></td>
         <td>
           <%= number_with_precision(clienttransaction.transactioninvoices.map{|so| so.amount}.compact.sum, precision: 2) if  clienttransaction.transactioninvoices.present? %>
         </td>
         <!-- <td><%#= clienttransaction.transactioninvoices.present? ?
          clienttransaction.transactioninvoices.first.reference_no : '---' %></td> -->
        <td>
          <%= link_to 'Edit', edit_clienttransaction_path(clienttransaction), class: "btn btn-primary", style: 'margin-bottom: 10px;' %>
          <%= link_to 'Delete', clienttransaction, method: :delete, data: { confirm: 'Are you sure?' } ,class: "btn btn-danger"%>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/clienttransactions/new.html.erb
<style type="text/css">
  input[type="submit"] { display: none; }
</style>


<h1>Transaction (Cash From Client)</h1>
<br>

<%= render 'form' %>

<div id="invoices" class="modal fade col-xs-10"  role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content col-xs-12 modal-lg" style="width: 157%;">
      <div class="modal-header">
        <h3>Select Invoice</h3>
        <button type="button" class="close" data-dismiss="modal">&times;</button>
      </div>
      <div class="modal-body">
        <table class="table table-hover" id="client_invoice">
          <thead>
          <tr>
            <th >Invoice Num</th>
            <th >Reference</th>
            <th >Amount</th>
            <th >Transaction Amount</th>
            <th >Last Paid</th>
            <th >Due Date</th>
            <th >Total Paid</th>
            <th >Notes</th>
          </tr>
          </thead>

          <tbody>
          </tbody>

        </table>

      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
      </div>
    </div>

  </div>
</div>

<script>
  $(function() {
    $(".tdate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date());
    $(".ddate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date(Date.now() + (30 * 24 * 60 * 60 * 1000)));
  });
</script>

app/views/clienttransactions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Payment Type:</strong>
    <td><%= @clienttransaction.setup.present? ? @clienttransaction.setup.typeofsetup: '---' %></td>
</p>

<p>
  <strong>Client Name:</strong>
        <td><%= @clienttransaction.client.present? ? @clienttransaction.client.name: '---' %></td>
</p>

<%= link_to 'Edit', edit_clienttransaction_path(@clienttransaction) %> |