config/routes.rb
Rails.application.routes.draw do

  get 'reports/clientdetail'=>'reports#clientdetail'
  get 'reports/transactionhistory'=>'reports#transactionhistory'
  get 'reports/vendordetail'=>'reports#vendordetail'
  get 'reports/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'reports/customersummary'=>'reports#customersummary'
  get 'reports/vendorsummary'=> "reports#vendorsummary"
  get 'reports/bankbalance'=> "reports#bankbalance"
  get 'reports/paymentdetail'=> "reports#paymentdetail"
  get 'reports/cashdetail'=> "reports#cashdetail"
  get 'reports/paymentsummary'=> "reports#paymentsummary"
  get 'reports/cashsummary'=> "reports#cashsummary"

  get 'invoices/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'invoices/summary_invoice/:client_id/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/:date_to'=>'invoices#summary_invoice'
  get 'invoices/invoicesummary'=>'invoices#invoicesummary'

  get 'public/privacy'

  get 'public/conditions'

  resources :transactionbills
  resources :vendortransactions
  resources :transactioninvoices
  resources :clienttransactions
  resources :setups
  resources :setups
  resources :bills
  resources :invoices do
    resources :line_items
  end

  resources :vendors
  resources :clients
  get 'history/index'
  get 'search/index'
  get 'landing' => 'search#landing'

  get 'users/send_email'
  get 'users/notes', as: "get__user_notes"
  post 'users/notes', as: "user_notes"
  get 'users/setup'
  get 'search/results'

  get "user/:id" => "users#user_profile", :as=> "user_profile"
  get 'invoices/invoices_of_a_single_client/:client_id' => 'invoices#invoices_of_a_single_client'
  
  get 'bills/bills_of_a_single_client/:vendor_id' => 'bills#bills_of_a_single_client'
  
  root to: 'search#index'
  devise_for :users
  resources :users
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  skip_before_filter :authenticate_user!, only: :landing

  def index
    @clients_count = current_user.clients.count
    @invoices_count = current_user.invoices.count
    @vendors_count = current_user.vendors.count
    @bills_count = current_user.bills.count
    @banks_count = current_user.setups.where(setuptype: 'bank').count
  end

  def results
    @search = params[:q]
    @invoices = current_user.invoices.search_invoices(@search)
    @clients = current_user.clients.search_clients(@search)
    @vendors = current_user.vendors.search_vendors(@search)
    @bills = current_user.bills.search_bills(@search)
  end

  def landing
    render layout: 'splash'
  end
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/search/index.html.erb
<div id="search-div">
	<div>
		<h1>
      SOBE Books
		</h1>
	<div/>
	
     <div>
		<form id="search-form" action="/search/results" method="get">
			<input id="search-q" class="form-control searching-textfield" name="q" type="text">
			<input id="search-b" type="submit" class="btn btn-primary" value="Search">
			<br>
		</form>
	</div>
	<div id="counts-all">
	
		<div id="clients-count">
			<div class="fa fa-user fa-3x individuaL-counts"> </div>
			<div class="individuaL-counts" > <%= link_to ("(" + @clients_count.to_s + ") Clients"), clients_path %></div>
			<div class="individuaL-counts" > $<%= number_with_precision(balance_due_from_clients, precision: 2, delimiter: ',') %> Due</div>
		</div>
		<div id="vendors-count">
			<div class="fa fa-user fa-3x individuaL-counts"> </div>
			<div class="individuaL-counts" > <%= link_to ("(" + @vendors_count.to_s + ") Vendors"), vendors_path %></div>
      <div class="individuaL-counts" > $<%= number_with_precision(owed_to_vendors, precision: 2, delimiter: ',') %> Owed</div>
		</div>
    <div id="vendors-count">
      <div class="fa fa-university fa-3x individuaL-counts"> </div>
      <div class="individuaL-counts" > <%=  link_to ("(" + @banks_count.to_s + ") Banks"), 'javascript:' %></div>
      <div class="individuaL-counts" > $<%= number_with_precision(bank_balance, precision: 2, delimiter: ',') %> Balance</div>
    </div>
		<div id="invoices-count">
			<div class="fa fa-file-pdf-o fa-3x individuaL-counts"> </div>
			<div class="individuaL-counts" > <%= link_to ("(" + @invoices_count.to_s + ") Invoices"), invoices_path %></div>
      <div class="individuaL-counts" > &nbsp; </div>
      </div>
		<div id="invoices-count">
			<div class="fa fa-file-pdf-o fa-3x individuaL-counts"> </div>
			<div class="individuaL-counts" > <%= link_to ("(" + @bills_count.to_s + ") Bills"), bills_path %></div>
      <div class="individuaL-counts" > &nbsp; </div>
		</div>

		
	</div>

</div>
</div>

app/views/search/landing.html.erb
<div id="skipnav"><a href="#maincontent">Skip to main content</a></div>

    <!-- Navigation -->
    <nav id="mainNav" class="navbar navbar-default navbar-fixed-top navbar-custom">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header page-scroll">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                    <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                </button>
                <a class="navbar-brand" href="#page-top">[SOBE Books]</a>
            </div>

            <!-- /.navbar-collapse -->
        </div>
        <!-- /.container-fluid -->
    </nav>

    <!-- Header -->
    <header>
        <div class="container" id="maincontent" tabindex="-1">
            <div class="row">
                <div class="col-lg-12">
                <span class="skills"><a href="">Cloud-based</a>, <a href=""> Containerized</a>, <a href="">  Open Source</a> App</span>
                    <div class="intro-text">
                       <h4 class="name">Download in your favourite language from our Github Repositories</h4>
                       <ul class="languages">
                       <li><a href="https://github.com/osvaldomeirino/sobeBooks">Ruby</a> </li>
                       <li><a href="javascript:">Java</a> </li>
                       <li><a href="javascript:">Python</a> </li>
                       <li><a href="javascript:">C# </a></li>
                       <li><a href="javascript:">PHP</a></li>
                       <li><a href="javascript:">NodeJS</a></li>
                       </ul>
                    </div>
                </div>
            </div>
        </div>
    </header>

    <!-- About Section -->
    <section id="about">
        <div class="container source">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="hd-1">Open Source Business Apps</h2>
                </div>
            </div>
             <div class="row">
               <div class="col-lg-3  col-sm-3">
                    <ul class="source-list">
                    <li>Sobe<b>Books</b></li>
                    <li>Sobe<b>CRM</b></li>
                    <li>Sobe<b>Supply</b></li>
                    </ul>
                </div>
                <div class="col-lg-3  col-sm-3">
                    <ul class="source-list">
                    <li>Sobe<b>Books</b></li>
                    <li>Sobe<b>CRM</b></li>
                    <li>Sobe<b>Supply</b></li>
                    </ul>
                </div>
                <div class="col-lg-3  col-sm-3">
                    <ul class="source-list">
                    <li>Sobe<b>Books</b></li>
                    <li>Sobe<b>CRM</b></li>
                    <li>Sobe<b>Supply</b></li>
                    </ul>
                </div>
                <div class="col-lg-3  col-sm-3">
                    <ul class="source-list">
                    <li>Sobe<b>Books</b></li>
                    <li>Sobe<b>CRM</b></li>
                    <li>Sobe<b>Supply</b></li>
                    </ul>
                </div>
               
              
            </div>
        </div>
    </section>

     <!-- About Section -->
    <section id="platforms">
        <div class="container platforms">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="hd-1">Deploy in your favourite cloud platform</h2>
                </div>
            </div>
             <div class="row">
               <div class="col-lg-12  col-sm-12">
                    <ul class="platforms-list">
                    <li><img src="img/amazon.png" width="200px"></li>
                    <li><img src="img/azure.png" width="240px"></li>
                    <li><img src="img/google.png" width=""></li>
                    <li><img src="img/heroku.png" width="200px"></li>
                    <li><img src="img/engineyard.jpg" width="240px"></li>
                   
                    </ul>
                </div>
            </div>
        </div>
    </section>
     <!-- About Section -->
    <section id="application-type-1">
        <div class="container source">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="hd-1">What are cointainer based Applications?</h2>
                </div>
            </div>
            <div class="row margin-50">
                <div class="col-lg-12">
                    <p class="details"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                </div>
               
               
            </div>
        </div>
    </section>
    <section id="application-type-2">
        <div class="container source">
            <div class="row">
                <div class="col-lg-12 text-center">
                    <h2 class="hd-1">What are open sourced Applications?</h2>
                </div>
            </div>
            <div class="row margin-50">
                <div class="col-lg-12">
                    <p class="details"> is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.</p>
                </div>
               
               
            </div>
        </div>
    </section>

app/views/search/results.html.erb
<div class="row" style="margin-bottom:10px;">
	<div id="search-heading" class="col-md-4" >	
		<h1 style="display:inline;">Search Results</h1>	
	</div>
	
</div>
<div id= "search-result" >









	<div class="col-xs-3"> <!-- required for floating -->
	    <!-- Nav tabs -->
	    <ul class="nav nav-tabs tabs-left nav nav-tabs" id="myTab">
	    	<%if @invoices.count>0 %>
	      		<li class="active"><a href="#portfolio-search-results" data-toggle="tab">Invoices(<%=@invoices.count%>)</a></li>
	      	<%end%>
	      	<%if @clients.count>0 %>
	      		<li ><a href="#products-search-results" data-toggle="tab">Clients(<%=@clients.count%>)</a></li>
	      	<%end%>

			<%if @vendors.count>0 %>
				<li><a href="#apps-search-results" data-toggle="tab">Vendors(<%=@vendors.count%>)</a></li>
			<%end%>
			<%if @bills.count>0 %>
				<li><a href="#bills-search-results" data-toggle="tab">Bills(<%=@bills.count%>)</a></li>
			<%end%>
			



	    </ul>
	</div>

	<div class="col-xs-9">
	<% if @invoices.present? || @clients.present? || @vendors.present? || @bills.present? %>
	    <!-- Tab panes -->
	    <div class="tab-content">
	      <%active_tab=false%>
	      <%if @invoices.count>0%>
	      	<%active_tab=true%>		
	      <%end%>

	      <%if active_tab%>
	      	<div class="tab-pane active" id="portfolio-search-results">
	      <%else%>
	      	<div class="tab-pane" id="portfolio-search-results">
	      <%end%>
    
			<table class="table table-striped table-hover table-responsive table-app-setup six-columned">
			  <thead>
			    <tr>
			    <th>Client Name </th>  
			  	<th>Invoice Date </th> 
			  	<th>Invoice# </th>
			  	<th> Reference </th>
			  	<th> Amount </th> 
			  	<th> Balance </th> 
			  	<th>Last Paid </th> 
			     <th>Total Paid </th> 
			     <th>Status</th> 




			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @invoices.each do |invoice| %>
			      <tr>
			      	<td><%= invoice.client.present? ? invoice.client.name : '---'%></td>
			      	<td><%= invoice.created_at%></td>
			        <td><%= invoice.id%></td>
			        <td><%= invoice.reference%></td>
			        <td><%= invoice.amount%></td>
			        <td><%= invoice.balance%></td>
			        <td><%= invoice.lastpayment%></td>
			        <td><%= invoice.totalpaid%></td>
			        <td><%= invoice.status%></td>

                 </tr>
			    <% end %>
			  </tbody>
			</table>
    

	      </div>

	      <%if @clients.count>0 && !active_tab%>
	      	<%active_tab=true%>
	      	<%temp_var=true%>
	      <%else%>
	      	<%temp_var=false%>		
	      <%end%>

	      <%if active_tab && temp_var%>
	      	<div class="tab-pane active" id="products-search-results">
	      <%else%>
	      	<div class="tab-pane" id="products-search-results">
	      <%end%>

	      

			<table class="table">
			  <thead>
			    <tr>
			    	<!-- clinet's fields here  -->
			      <th>Client name</th>
			      <th>Company Name</th>
			      <th>Email</th>
			      <th>Phone</th>
			      <th>Identifier</th>
			      <th>Reference</th>
			      <th>Notes</th>
			     <th>Status</th> 


			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @clients.each do |client| %>
			      
			      <tr>
			        <td><%= client.name? ? client.name : "---" %></td>
			        <td><%= client.company_name%></td>
			        <td><%= client.email%></td>
			        <td><%= client.phone%></td>
			        <td><%= client.identifier%></td>
			        <td><%= client.reference%></td>
			        <td><%= client.notes%></td>
			        <td><%= client.status%></td>





			      </tr>
			    <% end %>
			  </tbody>
			</table>

	      </div>

	      <%if @vendors.count>0 && !active_tab%>
		     <%active_tab=true%>
		     <%temp_var=true%>
	      <%else%>
	      	<%temp_var=false%>		
	      <%end%>

	      <%if active_tab && temp_var%>
	      	<div class="tab-pane active" id="apps-search-results">
	      <%else%>
	      	<div class="tab-pane" id="apps-search-results">
	      <%end%>

	      
	      	<!-- vendor's fields here  -->
			<table class="table">
			  <thead>
			    <tr>
			      <th>Vendor name</th>
			      <th>Company Name</th>
			      <th>Email</th>
			      <th>Phone</th>
			      <th>Identifier</th>
			      <th>Reference</th>
			      <th>Notes</th>
			  	   <th>Status</th> 
			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @vendors.each do |vendor| %>
			      <tr>
			      	<td><%= vendor.name%></td>
			      	<td><%= vendor.company_name%></td>
			      	<td><%= vendor.email%></td>
			       <td><%= vendor.phone%></td>
			       <td><%= vendor.identifier%></td>
			       <td><%= vendor.reference%></td>
			       <td><%= vendor.notes%></td>
			       <td><%= vendor.status%></td>

			      </tr>
			    <% end %>
			  </tbody>
			</table>

	     	</div>


	      <%if @bills.count>0 && !active_tab%>
		     <%active_tab=true%>
		     <%temp_var=true%>
	      <%else%>
	      	<%temp_var=false%>		
	      <%end%>

	      <%if active_tab && temp_var%>
	      	<div class="tab-pane active" id="bills-search-results">
	      <%else%>
	      	<div class="tab-pane" id="bills-search-results">
	      <%end%>

	      
	     	<table class="table table-striped table-hover table-responsive table-app-setup six-columned">
			  <thead>
			    <tr>
			    <th>Vendor Name </th>  
			  	<th>Vendor Date </th> 
			  	<th>Bill# </th>
			  	<th> Reference </th>
			  	<th> Amount </th> 
			  	<th> Balance </th> 
			  	<th>Last Paid </th> 
			     <th>Total Paid </th> 
			  	   <th>Status</th> 




			      <th colspan="3"></th>
			    </tr>
			  </thead>

			  <tbody>
			    <% @bills.each do |bill| %>
			      <tr>
			      	<td><%= bill.vendor.present? ? bill.vendor.name : '---'%></td>
			      	<td><%= bill.created_at%></td>
			        <td><%= bill.id%></td>
			        <td><%= bill.reference%></td>
			        <td><%= bill.amount%></td>
			        <td><%= bill.balance%></td>
			        <td><%= bill.lastpayment%></td>
			        <td><%= bill.totalpaid%></td>
			        <td><%= bill.status%></td>


                 </tr>
			    <% end %>
			  </tbody>
			</table>

	     	</div>

 		  
 		  
	  	
	    </div>
	<% else %>
		<div class="text-center"> <h3>Nothing found...</h3></div>
	<% end %>
	</div>  
</div>
<script>
    $('#myTab a').click(function (e) {
        e.preventDefault();
        $(this).tab('show');
    });

    // store the currently selected tab in the hash value
    $("ul.nav-tabs > li > a").on("shown.bs.tab", function (e) {
        var id = $(e.target).attr("href").substr(1);
        window.location.hash = id;
    });

    // on load of the page: switch to the currently selected tab
    var hash = window.location.hash;
    $('#myTab a[href="' + hash + '"]').tab('show');
</script>