config/routes.rb
Rails.application.routes.draw do

  get 'reports/clientdetail'=>'reports#clientdetail'
  get 'reports/transactionhistory'=>'reports#transactionhistory'
  get 'reports/vendordetail'=>'reports#vendordetail'
  get 'reports/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'reports/customersummary'=>'reports#customersummary'
  get 'reports/vendorsummary'=> "reports#vendorsummary"
  get 'reports/bankbalance'=> "reports#bankbalance"
  get 'reports/paymentdetail'=> "reports#paymentdetail"
  get 'reports/cashdetail'=> "reports#cashdetail"
  get 'reports/paymentsummary'=> "reports#paymentsummary"
  get 'reports/cashsummary'=> "reports#cashsummary"

  get 'invoices/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'invoices/summary_invoice/:client_id/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/:date_to'=>'invoices#summary_invoice'
  get 'invoices/invoicesummary'=>'invoices#invoicesummary'

  get 'public/privacy'

  get 'public/conditions'

  resources :transactionbills
  resources :vendortransactions
  resources :transactioninvoices
  resources :clienttransactions
  resources :setups
  resources :setups
  resources :bills
  resources :invoices do
    resources :line_items
  end

  resources :vendors
  resources :clients
  get 'history/index'
  get 'search/index'
  get 'landing' => 'search#landing'

  get 'users/send_email'
  get 'users/notes', as: "get__user_notes"
  post 'users/notes', as: "user_notes"
  get 'users/setup'
  get 'search/results'

  get "user/:id" => "users#user_profile", :as=> "user_profile"
  get 'invoices/invoices_of_a_single_client/:client_id' => 'invoices#invoices_of_a_single_client'
  
  get 'bills/bills_of_a_single_client/:vendor_id' => 'bills#bills_of_a_single_client'
  
  root to: 'search#index'
  devise_for :users
  resources :users
end

app/models/bill.rb
# == Schema Information
#
# Table name: bills
#
#  id               :integer          not null, primary key
#  reference        :string
#  notes            :string
#  amount           :decimal(, )
#  lastpaid         :decimal(, )
#  totalpaid        :decimal(, )
#  status           :string
#  user_id          :integer
#  vendor_id        :integer
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#  balance          :decimal(, )
#  lastpayment      :date
#  transaction_date :date
#  duedate          :date
#  setup_id         :integer
#

class Bill < ActiveRecord::Base
  belongs_to :user
  belongs_to :vendor
  belongs_to :setup
  has_many :transactionbills, dependent: :destroy

  before_save :set_balance

  include PgSearch
  pg_search_scope :search_bills, :against => [:reference,:amount,:status]

  def as_json(options)
    super(:methods => [:balance_amount]).merge(:vendor => vendor.as_json, :transaction_bills => transactionbills.order("id DESC").as_json)
  end

  STATUSES = ['Unpaid','Draft']

  def statuses
    STATUSES[read_attribute(:statuses)]
  end

  def balance_amount
    self.amount.to_f - self.totalpaid.to_f
  end

  def set_balance
    self.balance = balance_amount
  end

  STATUSES.each_with_index do |status, index|
    method_name = status.gsub(" ", "_").underscore
    define_method "#{method_name}!" do
      update_attribute(:statuses, index)
    end

    scope method_name, lambda { where(statuses: index) }
  end

  scope :unclosed, lambda { where.not(statuses: STATUSES[0]) }
end

app/controllers/bills_controller.rb
class BillsController < ApplicationController
  before_action :set_bill, only: [:show, :edit, :update, :destroy]

  # GET /bills
  # GET /bills.json
  def index
    @bills = current_user.bills.order("id DESC")
  end

  # GET /bills/1
  # GET /bills/1.json
  def bills_of_a_single_client
   vendor = Vendor.find(params[:vendor_id])
   @bills =  vendor.bills.where(:status=>'unpaid')

   respond_to do |format|
    format.json { render  json: @bills, status: :ok }
   end
  end

  def show
  end

  # GET /bills/new
  def new
    @bill = Bill.new
  end

  # GET /bills/1/edit
  def edit
  end

  # POST /bills
  # POST /bills.json
  def create
    @bill = Bill.new(bill_params)
    @bill.user_id = current_user.id
    @bill.totalpaid = @bill.amount if @bill.status =='paid'

    respond_to do |format|
      if @bill.save
        set_formatted_dates()
        format.html { redirect_to bills_url, notice: 'Bill was successfully created.' }
        format.json { render :show, status: :created, location: @bill }
      else
        format.html { render :new }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /bills/1
  # PATCH/PUT /bills/1.json
  def update
    respond_to do |format|
      if @bill.update(bill_params)
        set_formatted_dates()
        format.json { render json: @bill.to_json(include: :vendor), status: :ok }
      else
        format.html { render :edit }
        format.json { render json: @bill.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bills/1
  # DELETE /bills/1.json
  def destroy
    @bill.destroy

    respond_to do |format|
      format.html { redirect_to bills_url, notice: 'Bill was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.

    def set_formatted_dates
      @bill.update_attribute(:duedate, formatted_date(bill_params[:duedate])) if bill_params[:duedate].present?
      @bill.update_attribute(:transaction_date, formatted_date(bill_params[:transaction_date])) if bill_params[:transaction_date].present?
    end

    def set_bill
      @bill = Bill.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def bill_params
      params.require(:bill).permit(:reference, :notes, :amount, :lastpaid, :totalpaid,
       :status, :vendor_id,:balance,:lastpayment, :duedate, :transaction_date, :setup_id)
    end
end

app/helpers/bills_helper.rb
module BillsHelper
end

app/views/bills/_form.html.erb
<%= simple_form_for(@bill) do |f| %>
  <%= f.error_notification %>
  <div class="form-inputs col-md-6 ">
    <%= f.input :transaction_date, :as => :string, class: 'form-control', input_html: { class: 'tdate' } %>
    <%= f.input :duedate, as: :string, required: true, input_html: { class: 'ddate' } %>

    <%= f.input :reference , required: true%>
    <%= f.input :amount , required: true%>
    <%= f.input :notes , required: true%>

    <%= f.select_tag "bill[setup_id]",
                     options_for_select(current_user.setups.where(:setuptype=>'expense').map{|s|[s.typeofsetup, s.id]},
                                        @bill.setup_id),:id=>"setup_id" , prompt: "Select Expense ID",
                     class: 'form-control' , required: true %>
    <br>

    <%= f.select_tag "bill[vendor_id]",
                     options_for_select(current_user.vendors.all.order_by_name.map{|s|[s.company_name, s.id]}),
                     :id=>"bill" , prompt: "Select Vendor", class: 'form-control' %>
  <br>
   <%= f.select_tag "bill[status]", options_for_select(invoice_status_list,
    @bill.status), :id=>"status", class: 'form-control' ,required: true%>
  <br>

   <div class="form-actions">
    <%= f.button :submit, class: 'btn btn-primary' %>
  </div>
  </div>
 
<% end %>

app/views/bills/_header.html.erb
<tr>
  <th >Bill Num</th>
  <th >Reference</th>
  <th >Vendor</th>
  <th >Expense</th>
  <th >Amount</th>
  <th >Balance</th>
  <!--<th >Last Paid</th>-->
  <th >Transaction Date</th>
  <th >Due Date</th>
  <th >Status</th>
</tr>

app/views/bills/_row.html.erb
<tr>
  <td><%= link_to bill.id, bill %></td>
  <td><%= bill.reference %></td>
  <td><%= bill.vendor.present? ? bill.vendor.company_name : "--" %></td>
  <td><%= bill.setup.present? ? bill.setup.typeofsetup : "--" %></td>
  <!--<td>-->
    <!--<%#= bill.lastpayment %>-->
  <!--</td>-->
  <td>
    <%= number_with_precision(bill.amount, precision: 2) %>
  </td>
  <td>
    <%= number_with_precision(bill.balance, precision: 2) %>
  </td>
  <td><%= display_formatted_date(bill.transaction_date) %></td>
  <td><%= display_formatted_date(bill.duedate) %></td>
  <td><%= bill.status.present? ? bill.status.titleize : "--" %>
  </td>
  <td>
    <%= link_to 'Edit', bill, class: "btn btn-primary" %>
    <%= link_to 'Delete', bill, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %>
  </td>
</tr>

app/views/bills/edit.html.erb
<h1>Editing Bill</h1>

<%= render 'form' %>

app/views/bills/index.html.erb
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
</head>

<body>

<div class="row">
  <div class="col-xs-6">
  </div>
  <div class="col-xs-6">
    <p style="text-align: right;"><b>Total Owed to Vendors: </b>
      <span>$<%= number_with_precision(owed_to_vendors, precision: 2, delimiter: ',') %></span></p>
  </div>
</div>

<div class="row">
  <div class="col-xs-6">
    <h2>Bills</h2>
  </div>

  <div class="col-xs-6">
    <%= link_to 'New Bill', new_bill_path,
                class:"btn btn-primary pull-right new-btn-top-right" %>
  </div>
</div>
<br/>

<div class="container">
  <!-- Nav tabs -->
  <ul class="nav nav-tabs " role="tablist">
    <li class="active col-xs-3 tab-pading">
      <a href="#home" role="tab" data-toggle="tab">
        All
      </a>
    </li>
    <li class="col-xs-3 tab-pading"><a href="#profile" role="tab" data-toggle="tab">
      Paid
    </a>
    </li>
    <li class="col-xs-3 tab-pading">
      <a href="#messages" role="tab" data-toggle="tab">
        Unpaid
      </a>
    </li>
    <li class="col-xs-3 tab-pading">
      <a href="#settings" role="tab" data-toggle="tab">
        Past Due
      </a>
    </li>
  </ul>
  <!-- Tab panes -->
  <div id="tab-content" class="tab-content">
    <div class="tab-pane fade active in" id="home">
      <table class="table table-hover table-striped">
        <thead>
          <%= render 'bills/header' %>
        </thead>

        <tbody>
        <% @bills.each do |bill| %>
            <%= render 'bills/row', bill: bill %>
        <% end %>
        </tbody>
      </table>
    </div>
    <div class="tab-pane fade" id="profile">

      <table class="table table-hover table-striped">
        <thead>
          <%= render 'bills/header' %>
        </thead>

        <tbody>
        <% @bills.each do |bill| %>
            <% if bill.status == "paid" %>
              <%= render 'bills/row', bill: bill %>
            <% end %>
        <% end %>
        </tbody>
      </table>

    </div>
    <div class="tab-pane fade" id="messages">

      <table class="table table-hover table-striped">
        <thead>
          <%= render 'bills/header' %>
        </thead>

        <tbody>
        <% @bills.each do |bill| %>
            <% if bill.status == "unpaid" %>
                <%= render 'bills/row', bill: bill %>
            <% end %>
        <% end %>

        </tbody>
      </table>
    </div>
    <div class="tab-pane fade" id="settings">
      <table class="table table-hover table-striped">
        <thead>
          <%= render 'bills/header' %>
        </thead>

        <tbody>
        <% @bills.each do |bill| %>
            <% if bill.status == "past due" %>
                <%= render 'bills/row', bill: bill %>
            <% end %>
        <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

</div>
</body>
</html>

app/views/bills/new.html.erb
<h1>New Bill</h1>

<%= render 'form' %>

<script>
  $(function() {
    $(".tdate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date());
    $(".ddate").datepicker({ dateFormat: 'mm-dd-yy' }).datepicker("setDate", new Date(Date.now() + (30 * 24 * 60 * 60 * 1000)));
  });
</script>

app/views/bills/show.html.erb
<div class="container ">
  <div class="row">
    <div class="col-xs-5">
      <h2>Bill Detail</h2>
    </div>
    <div class="col-xs-7">
<span id="bill-edit" style="margin-top: 20px;" class="btn btn-info pull-right" data-invoice-edit-url="<%= edit_bill_path(@bill) %>"> 
    Edit Bill</span>
    </div>
  </div>
  <br>
  <table class="table table-hover table-striped">
    <tbody>
    <tr>
      <td><b>Bill Num</b></td>
      <td><%= @bill.id %></td>
    </tr>
    <tr>
      <td><b>Vendor Name</b></td>
      <td id="bill-vendor-name"><%= @bill.vendor.present? ? @bill.vendor.company_name : "---"%></td>
    </tr>
    <tr>
      <td><b>Reference</b></td>
      <td id="bill-reference"><%= @bill.reference %></td>
    </tr>
    <tr>
      <td><b>Notes</b></td>
      <td id="bill-notes"><%= @bill.notes %></td>
    </tr>
    <tr>
      <td><b>Updated</b></td>
      <td id="bill-date-update"><%= @bill.updated_at.to_date %></td>
    </tr>
    <!--<tr>-->
      <!--<td><b>Last Paid</b></td>-->
      <!--<td id="bill-lastpaid"><%#= number_with_precision(@bill.lastpayment, precision: 2) %></td>-->
    <!--</tr>-->
    <tr>
      <td><b>Amount</b></td>
      <td id="bill-amount"><%= number_with_precision(@bill.amount, precision: 2) %></td>
    </tr>
    <tr>
      <td><b>Balance</b></td>
      <td id="bill-balance"><%= number_with_precision(@bill.balance, precision: 2) %></td>
    </tr>

    <tr>
      <td><b>Transaction Date</b></td>
      <td id="bill-tdate"><%= display_formatted_date(@bill.transaction_date) %></td>
    </tr>

    <tr>
      <td><b>Due Date</b></td>
      <td id="bill-ddate"><%= display_formatted_date(@bill.duedate) %></td>
    </tr>

    <tr>
      <td><b>Total paid</b></td>
      <td id="bill-lastpaid"><%= number_with_precision(@bill.totalpaid, precision: 2) %></td>
    </tr>

    <tr>
      <td><b>Status</b></td>
      <td id="bill-status"><%= @bill.status.present? ? @bill.status.capitalize : '---' %></td>
    </tr>

    </tbody>
  </table>



  <div id="edit_bill_modal" class="modal fade" role="dialog">
    <div class="modal-dialog">

      <!-- Modal content-->
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal">&times;</button>
          <h4 class="modal-title">Edit Item</h4>
        </div>
        <div class="modal-body">
          <%= simple_form_for(@bill,remote: true) do |f| %>
              <%= f.error_notification %>
              <div class="form-inputs">
                <%= f.input :transaction_date, as: :string, required: true,
                            input_html: { value: "#{display_formatted_date(@bill.transaction_date)}", class: 'tdate' } %>
                <%= f.input :duedate, as: :string, required: true,
                            input_html: { value: "#{display_formatted_date(@bill.duedate)}", class: 'ddate' } %>
                <%= f.input :reference, required: true%>
                <%= f.input :notes, required: true%>
                <%= f.input :amount, input_html: { value: "#{number_with_precision(@bill.amount, precision: 2)}" } ,required: true%>

                <%= f.label :setup_id, 'Expense ID' %>
                <%= f.select_tag "bill[setup_id]",
                                 options_for_select(current_user.setups.where(:setuptype=>'expense').map{|s|[s.typeofsetup, s.id]},
                                                    @bill.setup_id),:id=>"setup_id" , prompt: "Select Expense ID",
                                 class: 'form-control', required: true %>

                <%= f.label :Vendor %>
                <%= f.select_tag "bill[vendor_id]", options_for_select(current_user.vendors.all.order_by_name.map{|s|[s.company_name, s.id]},
                                                                       @bill.vendor_id),:id=>"bill" , prompt: "Select Vendor", class: 'form-control' %>
                <br>
                <%= f.select_tag "bill[status]", options_for_select(invoice_status_list, @bill.status),
                                 id: "status", class: 'form-control' %>
              </div>
              <br/><br/>
              <div class="form-actions">
                <%= f.button :submit, 'Update Bill', class: 'btn btn-primary' %>
              </div>
          <% end %>

        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        </div>
      </div>

    </div>
  </div>

</div>

<script>
  $(document).on('click', '#bill-edit', function(event) {
    $("#edit_bill_modal").modal('show');
  });

  $(document).on('ajax:success', '.edit_bill', function(event, data, status, xhr) {
    $("#edit_bill_modal").modal('hide');

    $("#bill-date-update").text(data.updated_at.to_date);
    $("#bill-reference").text(data.reference);
    $("#bill-balance").text(parseFloat(data.balance).toFixed(2));
    $("#bill-lastpaid").text(parseFloat(data.lastpaid).toFixed(2));
    $("#bill-amount").text(parseFloat(data.amount).toFixed(2));
    $("#bill-notes").text(data.notes);
    $("#bill-tdate").text(data.transaction_date);
    $("#bill-ddate").text(data.duedate);
    $("#bill-status").text(data.status);
    $('#bill-status').css('textTransform', 'capitalize');

    $("#bill-vendor-name").text(data.vendor.name);
  });

</script>