config/routes.rb
Rails.application.routes.draw do

  get 'reports/clientdetail'=>'reports#clientdetail'
  get 'reports/transactionhistory'=>'reports#transactionhistory'
  get 'reports/vendordetail'=>'reports#vendordetail'
  get 'reports/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'reports/customersummary'=>'reports#customersummary'
  get 'reports/vendorsummary'=> "reports#vendorsummary"
  get 'reports/bankbalance'=> "reports#bankbalance"
  get 'reports/paymentdetail'=> "reports#paymentdetail"
  get 'reports/cashdetail'=> "reports#cashdetail"
  get 'reports/paymentsummary'=> "reports#paymentsummary"
  get 'reports/cashsummary'=> "reports#cashsummary"

  get 'invoices/downloadinvoice/:id'=>'invoices#downloadinvoice'
  get 'invoices/summary_invoice/:client_id/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/'=>'invoices#summary_invoice'
  get 'invoices/summary_invoice/:client_id/:client_type/:date_from/:date_to'=>'invoices#summary_invoice'
  get 'invoices/invoicesummary'=>'invoices#invoicesummary'

  get 'public/privacy'

  get 'public/conditions'

  resources :transactionbills
  resources :vendortransactions
  resources :transactioninvoices
  resources :clienttransactions
  resources :setups
  resources :setups
  resources :bills
  resources :invoices do
    resources :line_items
  end

  resources :vendors
  resources :clients
  get 'history/index'
  get 'search/index'
  get 'landing' => 'search#landing'

  get 'users/send_email'
  get 'users/notes', as: "get__user_notes"
  post 'users/notes', as: "user_notes"
  get 'users/setup'
  get 'search/results'

  get "user/:id" => "users#user_profile", :as=> "user_profile"
  get 'invoices/invoices_of_a_single_client/:client_id' => 'invoices#invoices_of_a_single_client'
  
  get 'bills/bills_of_a_single_client/:vendor_id' => 'bills#bills_of_a_single_client'
  
  root to: 'search#index'
  devise_for :users
  resources :users
end

app/models/line_item.rb
# == Schema Information
#
# Table name: line_items
#
#  id          :integer          not null, primary key
#  price       :decimal(, )
#  description :string
#  quantity    :integer
#  invoices_id :integer
#  created_at  :datetime
#  updated_at  :datetime
#

class LineItem < ActiveRecord::Base
  validates_presence_of :price,:description,:quantity

  include Payday::LineItemable
  belongs_to :invoice, :foreign_key => "invoices_id"
end

app/controllers/line_items_controller.rb
class LineItemsController < ApplicationController
  before_action :set_line_item, only: [:show, :edit, :update, :destroy]

  # GET /line_items
  # GET /line_items.json
  def index
    @line_items = LineItem.all
  end

  # GET /line_items/1
  # GET /line_items/1.json
  def show
  end

  # GET /line_items/new
  def new
    @line_item = LineItem.new
  end

  # GET /line_items/1/edit
  def edit
    @invoice = Invoice.find(params[:invoice_id])
  end

  # POST /line_items
  # POST /line_items.json
  def create
    @line_item = LineItem.new(line_item_params)
    @line_item.invoices_id = params[:invoice_id]
    @invoice = Invoice.find(params[:invoice_id])

    respond_to do |format|
      if @line_item.save
        format.json { render json: @line_item, status: :ok }
      else
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /line_items/1
  # PATCH/PUT /line_items/1.json
  def update
    respond_to do |format|
      if @line_item.update(line_item_params)
        invoice = @line_item.invoice
        new_sum = invoice.line_items.collect{ |l| (l.price * l.quantity) }.sum.to_f
        invoice.amount = new_sum
        invoice.save
        format.json { render json: @line_item, status: :ok }
      else
        format.json { render json: @line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /line_items/1
  # DELETE /line_items/1.json
  def destroy
    invoice = @line_item.invoice

    if @line_item.destroy
      new_sum = invoice.line_items.collect{|l| (l.price * l.quantity)}.sum.to_f
      invoice.amount = new_sum
      invoice.save
      respond_to do |format|
        format.json { render json: @line_item, status: :ok }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_line_item
      @line_item= LineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def line_item_params
      params.require(:line_item).permit(:price, :description, :quantity, :invoice_update_amount)
    end
end

app/helpers/line_items_helper.rb
module LineItemsHelper
end

app/views/line_items/_form.html.erb
<%= simple_form_for([@invoice, @line_item]) do |f| %>
  <%= f.error_notification %>

   <div class="form-inputs">
    <%= f.input :price,required: true%>
        <%= f.input :description, required: true%>

    <%= f.input :quantity ,required: true%>

    


  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/line_items/edit.html.erb
<h1>Editing Line Item</h1>

<%= render 'form' %>

app/views/line_items/index.html.erb
<!DOCTYPE html>

<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

 </head> 

<body>
 
  <h1>Line Items</h1><br>
   
    <div class="container">
      <table class="table table-hover">
        <thead>
          <tr>
           <th >Price</th>
      <th >Description</th>
      <th >Quantity</th>
     



        </tr>
        </thead>

        <tbody>
    <% @line_items.each do |line_item| %>
      <tr>
         <td><%= line_item.price %></td>
            <td><%= line_item.description %></td>
             <td><%= line_item.quantity %></td>
              
            


        <td><%= link_to 'Show', line_item , class: "btn btn-success"  %></td>
        <td><%= link_to 'Edit', edit_line_item_path(line_item) ,class: "btn btn-info"%></td>
        <td><%= link_to 'Destroy', line_item, method: :delete, data: { confirm: 'Are you sure?' },class: "btn btn-danger" %></td>
      </tr>
      <% end %>
        </tbody>
      </table>

<br>

<%= link_to 'New Invoice', new_line_item_path , class:"btn btn-primary" %>
</div>
</body>
</html>

app/views/line_items/new.html.erb
<h1>New Line Item</h1>

<%= render 'form' %>

app/views/line_items/show.html.erb
<!DOCTYPE html>

<html>
<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  
</head> 

<body>
	<p id="notice"><%= notice %></p>

    <div class="container">
      <table class="table table-hover">
        <thead>
          <tr>
       <th >Price</th>
      <th >Description</th>
      <th >Quantity</th>
     


           
          </tr>
        </thead>
        <tbody>
            <tr>
              <td><%= @line_item.price %></td>
              <td><%= @line_item.description %></td>
              <td><%= @line_item.quantity %></td>
              
            

            </tr>   
        </tbody>
      </table>
      <%= link_to 'Edit', edit_invoice_line_item_path(params[:invoice_id], @line_item), class: "btn btn-info" %>
    </div>
</body>
</html>